table _Medidas
	lineageTag: 2b71c345-dddf-4f0e-9980-9d693ac1ef94

	measure 'Qtd Nome Ativo Text' = ```
			
			VAR TodosNomesAtivoDistintos =
			    VALUES(fat_fiscal[nome_ativo])
			VAR NomesAtivoApenasComData =
			    FILTER(
			        TodosNomesAtivoDistintos,
			        CALCULATE(
			            -- Conta quantas linhas têm data_atualizacao BLANK para o nome_ativo atual
			            COUNTROWS(
			                FILTER(fat_fiscal, ISBLANK(fat_fiscal[data_atualizacao]))
			            )
			        ) = 0 -- Mantém apenas os nome_ativo onde a contagem de BLANKs é zero
			    )
			VAR Numerador = COUNTROWS(NomesAtivoApenasComData)
			
			RETURN
			    Numerador & " / " 
			```
		lineageTag: b4285958-5b00-4ff7-b8ad-a48701b2911e

	measure 'Denominador Qtd' =
			
			CALCULATE(
			    DISTINCTCOUNT(fat_fiscal[nome_ativo]),
			    ALLEXCEPT(fat_fiscal, fat_fiscal[data_insercao])
			)
		formatString: 0
		lineageTag: f512a2e0-6f99-4402-ac4a-89dca196b40e

	measure 'Qtd Nome Ativo Text OK' = ```
			
			VAR Total =
			    DISTINCTCOUNT(fat_fiscal[nome_ativo])
			
			VAR OK =
			    CALCULATE(
			        DISTINCTCOUNT(fat_fiscal[nome_ativo]),
			        fat_fiscal[status_atualizacao] = "OK"
			    )
			
			RETURN
			    OK & " / " & Total
			
			```
		lineageTag: fe7a594e-827f-44dd-9cf7-b4d4278c47bc

	measure 'Check Loja Zerada' = ```
			
			VAR QtdVendas = COUNTROWS('view_plugpharma_lojas_dia')
			RETURN
			    IF(
			        ISBLANK(QtdVendas), 
			        0, -- Retorna 0 se NÃO tiver registro na view (é quem você quer)
			        1  -- Retorna 1 se tiver vendas
			    )
			```
		formatString: 0
		lineageTag: 61a27071-f33c-45a9-a2d3-a671f415570c

	measure 'Qtd Total Lojas Vendeu' = DISTINCTCOUNT(view_plugpharma_lojas_dia[cnpj_loja])
		formatString: 0
		lineageTag: c5f4b22c-781f-4ef6-861b-db2b8f0d5150

	measure 'Qtd Total Lojas' = DISTINCTCOUNT(bronze_lojas[cnpj])
		formatString: 0
		lineageTag: 99768dcd-0553-49ee-9f99-4086ba62d336

	measure 'Card Não Captada vs Total' = ```
			
			VAR LojasFiltradas = 
			    FILTER(
			        VALUES('bronze_lojas'[cnpj_s]), -- Cria uma lista virtual de lojas
			        [Check Loja Zerada] = 0             -- Aplica SUA lógica em cada uma (0 = Não Vendeu)
			    )
			
			VAR Numerador = COUNTROWS(LojasFiltradas)   -- Conta quantas sobraram (deve dar 5)
			VAR Denominador = COUNTROWS('bronze_lojas') -- Total de lojas
			
			RETURN
			    COALESCE(Numerador,0) & " / " & Denominador
			
			
			
			```
		lineageTag: 4d792405-3053-40dc-ab19-22c7ceb46228

	measure 'Card Captada vs Total' = ```
			
			VAR Numerador = DISTINCTCOUNT('view_plugpharma_lojas_dia'[cnpj_loja])
			VAR Denominador = COUNTROWS('bronze_lojas') -- Total de lojas
			
			RETURN
			    COALESCE(Numerador,0) & " / " & Denominador
			
			
			
			```
		lineageTag: 515a48e2-d7fa-4d81-bf01-12efc24aebc8

	measure 'Card Não Captada vs Captada' = ```
			
			VAR LojasFiltradas = 
			    FILTER(
			        VALUES('bronze_lojas'[cnpj_s]), -- Cria uma lista virtual de lojas
			        [Check Loja Zerada] = 0         -- Aplica SUA lógica em cada uma (0 = Não Vendeu)
			    )
			
			VAR Numerador = COUNTROWS(LojasFiltradas)   -- Conta quantas sobraram (deve dar 5)
			VAR Denominador = DISTINCTCOUNT(view_plugpharma_lojas_dia[cnpj_loja]) -- Total de lojas
			
			RETURN
			    Numerador & " / " & Denominador
			```
		lineageTag: 6cf27e9d-7f5f-420c-bdea-2d67bdb1845e

	measure 'Card Captada não ativa' = ```
			
			CALCULATE(
			    DISTINCTCOUNT(view_plugpharma_lojas_dia[cnpj_loja]),
			    TREATAS(
			        VALUES(view_plugpharma_lojas_dia[cnpj_loja]),
			        bronze_lojas[cnpj_s]
			    ),
			    bronze_lojas[ativo] = FALSE()
			)
			
			```
		formatString: 0
		lineageTag: 84984cb2-f504-4dd3-9a93-8b54f07a9fcd

	measure 'Captada nao ativa' = COALESCE(DISTINCTCOUNT(view_plugpharma_lojas_dia[cnpj_loja]),0)
		formatString: 0
		lineageTag: 11d87d6c-d03c-4f3d-9bd8-4b20bfc7b62e

	column Column
		formatString: 0
		lineageTag: 1e41f2f3-6d77-4651-8ed0-d01695ccc30e
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition _Medidas = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = fc61041ba326473281739719ac1276b5

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

