table fat_fiscal
	lineageTag: a9d274b4-b7b9-4944-af6b-e7df0a76bb16

	column id_log
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: a74eede0-1f34-421a-ab01-cedc8ff3a7b3
		summarizeBy: sum
		sourceColumn: id_log

		annotation SummarizationSetBy = Automatic

	column nome_workspace
		dataType: string
		sourceProviderType: nvarchar(255)
		lineageTag: 0f238e71-db4b-43c2-aded-5a9c8a2ec9f2
		summarizeBy: none
		sourceColumn: nome_workspace

		annotation SummarizationSetBy = Automatic

	column nome_ativo
		dataType: string
		sourceProviderType: nvarchar(255)
		lineageTag: 0eb97f29-46cd-41bf-861a-bb82fb32dc6d
		summarizeBy: none
		sourceColumn: nome_ativo

		annotation SummarizationSetBy = Automatic

	column tipo_ativo
		dataType: string
		sourceProviderType: nvarchar(30)
		lineageTag: 98c00774-385d-404d-ba5c-14cb28cbb082
		summarizeBy: none
		sourceColumn: tipo_ativo

		annotation SummarizationSetBy = Automatic

	column dias_sem_atualizar
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 61530ec6-6a34-4764-8c52-4be9e335f399
		summarizeBy: sum
		sourceColumn: dias_sem_atualizar

		annotation SummarizationSetBy = Automatic

	column status_atualizacao
		dataType: string
		sourceProviderType: nvarchar(50)
		lineageTag: 1de843ab-5236-4395-ab89-f79312e8a7f5
		summarizeBy: none
		sourceColumn: status_atualizacao

		annotation SummarizationSetBy = Automatic

	column data_atualizacao
		dataType: dateTime
		formatString: dd/mm/yyyy
		sourceProviderType: date
		lineageTag: d4219f8e-47b3-414b-91a0-694f5df41f67
		summarizeBy: none
		sourceColumn: data_atualizacao

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column hora_atualizacao
		dataType: dateTime
		formatString: Long Time
		sourceProviderType: time
		lineageTag: 20b9ea7d-2413-4535-89a4-6a78f64ab01f
		summarizeBy: none
		sourceColumn: hora_atualizacao

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column tipo_atualizacao
		dataType: string
		sourceProviderType: nvarchar(50)
		lineageTag: b10ee450-b3be-4f5b-9a9d-bd35646f8fa4
		summarizeBy: none
		sourceColumn: tipo_atualizacao

		annotation SummarizationSetBy = Automatic

	column data_insercao
		dataType: dateTime
		isNullable: false
		formatString: dd/mm/yyyy
		sourceProviderType: date
		lineageTag: bfc55e42-930b-4c67-8b1b-97c0b92c95da
		summarizeBy: none
		sourceColumn: data_insercao

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column hora_insercao
		dataType: dateTime
		isNullable: false
		formatString: Long Time
		sourceProviderType: time
		lineageTag: 4fa5b1c4-4491-4fd5-bf5e-c1e9687e3693
		summarizeBy: none
		sourceColumn: hora_insercao

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column hora_insercao_hh
		dataType: string
		sourceProviderType: nvarchar(2)
		lineageTag: 9e8b8685-b0ed-45ec-b6e3-5dd3bc7bc366
		summarizeBy: none
		sourceColumn: hora_insercao_hh

		annotation SummarizationSetBy = Automatic

	partition fat_fiscal = m
		mode: directQuery
		source =
				let
				    Fonte = MariaDB.Contents("10.48.12.20:3306;dbDrogamais", null, null),
				    fat_fiscal_Table = Fonte{[Name="fat_fiscal",Kind="Table"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(fat_fiscal_Table,{{"data_insercao", type date}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

